### PR TITLE
Fix Intel issues

### PR DESCRIPTION
**Pull request by adrian1234a**

### CODE REVIEW

**Comment by humberos** [comment]
What device ?

**Comment by adrian1234a** [comment]
Zenfone 2

**Comment by humberos** [comment]
oh, nice!
so, please could you submit this change through gerrit instance:
https://gerrit.omnirom.org

Thanks!

**Comment by adrian1234a** [comment]
how make this?

**Comment by humberos** [comment]
https://docs.omnirom.org
You can also ask Google help.

**Comment by adrian1234a** [comment]
git push ssh://adrian1234a@gerrit.omnirom.org:29418/android HEAD:refs/for/android-7.1
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by humberos** [comment]
Sorry @adrian1234a 
If you want to add patches to this project (which will be welcome) then you should be able to use Gerrit.
All that you need you will find just by Googling about that matter!
Yes, may you will need to invest some time learning about it.
Good luck!
See ya!

**Comment by adrian1234a** [comment]
verify this https://gerrit.omnirom.org/#/c/23751/ :D

**Pull request closed without merging**
