### PR TITLE
Missing repos

### PR DESCRIPTION
**Pull request by threadreaper**
Change-Id: Ic1c3fb56404efdea3ca2c148ca3cfd2fb1001222

There are repos listed in the manifest that no longer exist.  I searched for the packages mentioned just in case they've moved, but I didn't find them, so I just commented out the entries for now.   

Addresses a few reports of problems: see Issue #35

### CODE REVIEW

**Comment by Vachounet** [comment]
What about reading the readme ?

**Comment by threadreaper** [comment]
I read the README.md.   I assume you're referring to the README.md in the Android-10.0 branch that mentions the private repositories, which I had not read, because I wasn't pulling that repo.   In this repo, those repos are still included in the omni-default.xml file, and the README.md for this repo doesn't mention anything about them.   But my question is answered, so thank you all the same.

**Comment by htsmi** [comment]
Same issue on 9.0. Why not just remove them from the manifests? I don't understand what you accomplish here other than to cause people errors.

**Comment by simonmicro** [comment]
@Vachounet I agree. Remove that damn private stuff - in the internet are thousand guides how to build with Omni, but that change breaks **every F\*\*\*\* build**. Especially for newbies, which may don't want to understand `repo` for now, that is a killer!

**Pull request closed without merging**
